print("Sonlarni taqqoslash: True(rost) va False(yolgʻon)ga tekshirish. muallif:Oʻ.R.Odiljonov @lion_user86")
x=int(input("Birinchi sonni kirting: "))
y=int(input("Ikkinchi sonni kirting: "))
print(x==y)
print(x>y)
print(x<y)
print(x!=y)
print(x<=y)
print(x>=y)